### ISSUE TITLE
bl pets not working

### ISSUE THREAD

**Issue by Gurenji** [SaltyMonkey/no-more-wasted-bubbles#1]
Hello, 

I am having a issue where only the ''bl'' command works. Which also removes all boss attack notifications such as ''argog shows his true self'' in Red Refuge.

If I try to just go with the ''bl pets'' my pet will keep on spamming messages.

Perhaps I am doing something wrong here? Or perhaps something amiss with the code?

**Comment by SaltyMonkey** [comment]
try to reinstall it
